SiegeCombat/Controllers/LobbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SiegeCombat.Models;

namespace SiegeCombat.Controllers
{
    public class LobbyController : Controller
    {
        //
        // GET: /Lobby/
        SiegeCombat.Models.SiegeCombatEntities bd = new SiegeCombatEntities();

        public ActionResult Index()
        {
            Usuario usuario = (Usuario)Session["Usuario"];
            List<Jugador> jugadoresConectados = bd.Jugador.Where(j => (j.Estatus == "CONECTADO" || j.Estatus == "JUGANDO") && j.IdJugador != usuario.IdJugador).ToList();
            ViewBag.jugadores = jugadoresConectados;
            Jugador jugador = bd.Jugador.Find(usuario.IdJugador);
            List<Jugador> topTen = bd.Jugador.OrderByDescending(j => j.EXP).Take(10).ToList();
            ViewBag.top = topTen;
            return View(jugador);
            
        }

        public ActionResult Cargar() 
        {
            Usuario usuario = (Usuario)Session["Usuario"];
            List<Jugador> jugadoresConectados = bd.Jugador.Where(j => j.Estatus == "CONECTADO" || j.Estatus == "JUGANDO" && j.IdJugador != usuario.IdJugador).ToList();
            return Json(jugadoresConectados);
        }

        public ActionResult CerrarSesion()
        {
            try
            {
                Usuario usuario = (Usuario)Session["Usuario"];
                Jugador jugador = bd.Jugador.Find(usuario.IdJugador);
                jugador.Estatus = "DESCONECTADO";
                bd.Entry(jugador).State = System.Data.EntityState.Modified;
                bd.SaveChanges();
                Session["Usuario"] = null;
            }
            catch (Exception ex)
            {
                
            }
            return Json(new { result = true, url = Url.Action("Index", "Login") });
        }

        public ActionResult ObtenerInvitaciones()
        {
            try
            {
                Usuario usuario = (Usuario)Session["Usuario"];
                List<Invitaciones> invitacion = null;
                invitacion = bd.Invitaciones.Where(i => i.IdOponente == usuario.IdJugador && i.Estatus != 0).ToList();              
                bool valido = false;
                foreach (Invitaciones i in invitacion)
                {
                    if (i.Estatus == 1)
                    {
                        Session["Invitacion"] = i;
                        DateTime ahora = DateTime.Now;
                        TimeSpan tiempo = ahora - (DateTime)i.Fecha;
                        int diferencia = tiempo.Minutes;
                        if(diferencia <= 3)
                            return Json(new { result = true, url = Url.Action("Index", "Juego"), id = i.IdInvitaciones });
                    }                        
                }
                return Json(new { result = valido, url = Url.Action("Index", "Juego") });
            }
            catch (Exception ex)
            {
                return Json(false);
            }
            
        }

        public ActionResult HacerInvitacion(int oponente) 
        {
            try
            {
                Invitaciones invitacion = new Invitaciones();
                Usuario usuario = (Usuario)Session["Usuario"];
                Jugador jugador = bd.Jugador.Find(usuario.IdJugador);

                invitacion.Estatus = 1;
                invitacion.Fecha = DateTime.Now;
                invitacion.IdHost = jugador.IdJugador;
                invitacion.IdOponente = oponente;

                bd.Invitaciones.Add(invitacion);
                bd.SaveChanges();

                return Json(new { result = true });
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        public ActionResult Jugar()
        {
            Invitaciones invitacion = (Invitaciones)Session["Invitacion"];
            Usuario usuario = (Usuario)Session["Usuario"];
            Jugador jugador = (Jugador)Session["Jugador"];
            Session["Oponente"] = bd.Jugador.Find(invitacion.IdHost);
            
            jugador.Estatus = "JUGANDO";

            Partida partida = new Partida();
            partida.Fecha = DateTime.Now;
            partida.IdJugadorUno = jugador.IdJugador;
            partida.IdJugadorDos = (int)invitacion.IdHost;
            jugador = bd.Jugador.Find(jugador.IdJugador);

            bd.Partida.Add(partida);
            invitacion = bd.Invitaciones.Find(invitacion.IdInvitaciones);
            bd.Entry(invitacion).State = System.Data.EntityState.Modified;

            bd.Entry(jugador).State = System.Data.EntityState.Modified;
            bd.SaveChanges();
            Session["Partida"] = partida;
            Hubs.HubJuego.EmpezarPartida(partida.IdJugadorUno,partida.IdJugadorDos);
            return Json(new { result = true, url = Url.Action("Index", "Juego") });
        }

        public ActionResult Cancelar() {
            try
            {
                Invitaciones invitacion = (Invitaciones)Session["Invitacion"];
                invitacion = bd.Invitaciones.Find(invitacion.IdInvitaciones);
                invitacion.Estatus = 0;
                bd.Entry(invitacion).State = System.Data.EntityState.Modified;
                bd.SaveChanges();
            }
            catch (Exception ex)
            {
                return Json(false);
            }
            return Json(new { result = true });
        }

        public ActionResult ValidaOponente(int idOponente)
        {
            try
            {
                Jugador jugador = (Jugador)Session["Jugador"];
                Jugador oponente = bd.Jugador.Find(idOponente);
                Session["Oponente"] =  oponente;
                List<Invitaciones> invitacion = null;
                invitacion = bd.Invitaciones.Where(i => i.IdOponente == jugador.IdJugador && i.Estatus != 0).ToList();
                bool valido = false;
                foreach (Invitaciones i in invitacion)
                {
                    if (i.Estatus == 1)
                    {
                        Session["Invitacion"] = i;
                        DateTime ahora = DateTime.Now;
                        TimeSpan tiempo = ahora - (DateTime)i.Fecha;
                        int diferencia = tiempo.Minutes;
                        if (diferencia <= 3)
                            return Json(new { result = true, url = Url.Action("Index", "Juego"), id = i.IdInvitaciones });
                    }
                }
                if (jugador.IdJugador == idOponente)
                {
                    Partida partida = bd.Partida.Where(p => p.IdJugadorDos == jugador.IdJugador && p.Estatus == 0).First();
                    Session["Partida"] = partida;
                    return Json(new { result = true, url = Url.Action("Index", "Juego") });
                }
                else
                    return Json(new { result = false, url = Url.Action("Index", "Juego") });
            }
            catch (Exception)
            {
                return Json(false);
                throw;
            }
            return Json(new { result = true, url = Url.Action("Index", "Juego") });
        }
    }
}

SiegeCombat/Controllers/TiendaController.cs
using SiegeCombat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiegeCombat.Controllers
{
    public class TiendaController : Controller
    {
        //
        // GET: /Tienda/
        SiegeCombatEntities bd = new SiegeCombatEntities();
        public ActionResult Index()
        {
            Usuario usuario = (Usuario)Session["Usuario"];
            Jugador jugador = bd.Jugador.Find(usuario.IdJugador);
            return View(jugador);
        }

        public ActionResult ComprarMejora(int mejora)
        {
            bool valido = false;
            try
            {
                Usuario usuario = (Usuario)Session["Usuario"];
                Jugador jugador = bd.Jugador.Find(usuario.IdJugador);
                if (mejora == 1)
                    jugador.Mejora1 = true;
                else if (mejora == 2)
                    jugador.Mejora2 = true;
                else if (mejora == 3)
                    jugador.Mejora3 = true;
                bd.Entry(jugador).State = System.Data.EntityState.Modified;
                bd.SaveChanges();
                valido = true;
            }
            catch (Exception ex)
            {
               
            }
            return Json(new { result = valido, url = "" });
        }
    }
}

SiegeCombat/Views/Tienda/Index.cshtml
@model SiegeCombat.Models.Jugador
@{
    ViewBag.Title = "Siege Combat | Tienda";
}


<div class="row col-md-3" style="background-color:firebrick; height:800px">
    @if (Model.Imagen == "Joystick.png")
    {
        <img src="~/Content/imagenes/Joystick.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    else if (Model.Imagen == "Boo.png")
    {
        <img src="~/Content/imagenes/Boo.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    else if (Model.Imagen == "Mexico.png")
    {
        <img src="~/Content/imagenes/Mexico.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    else if (Model.Imagen == "España.png")
    {
        <img src="~/Content/imagenes/España.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    else if (Model.Imagen == "NewZealand.png")
    {
        <img src="~/Content/imagenes/NewZealand.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    else if (Model.Imagen == "Mario.png")
    {
        <img src="~/Content/imagenes/Mario.png" style="margin-left: 60px;margin-top: 20px;" />
    }
    <div><label style="font-size:18px;color:white;margin-left:90px;">@Model.Nickname</label></div>
    <div><label style="font-size:14px;color:white;margin-left:100px;margin-top:20px">EXP</label></div>
    <div>
        @if (Model.EXP < 500)
        {
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@Model.EXP" aria-valuemin="0" aria-valuemax="1000" style="width: 30%;">
                    @Model.EXP
                </div>
            </div>
        }
        else if (Model.EXP < 800)
        {
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@Model.EXP" aria-valuemin="0" aria-valuemax="1000" style="width: 50%;">
                    @Model.EXP
                </div>
            </div>
        }
        else
        {
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@Model.EXP" aria-valuemin="0" aria-valuemax="1000" style="width: 80%;">
                    @Model.EXP
                </div>
            </div>
        }
    </div>
    <div><label style="font-size:14px;color:white;margin-left:100px;margin-top:20px">NIVEL</label></div>
    <div>
        @if (Model.Nivel == 1)
        {
            <div class="progress">
                <div class="progress-bar-success" role="progressbar" aria-valuenow="@Model.Nivel" aria-valuemin="0" aria-valuemax="3" style="width: 30%;">
                    @Model.Nivel
                </div>
            </div>
        }
        else if (Model.Nivel == 2)
        {
            <div class="progress">
                <div class="progress-bar-success" role="progressbar" aria-valuenow="@Model.Nivel" aria-valuemin="0" aria-valuemax="3" style="width: 60%;">
                    @Model.Nivel
                </div>
            </div>
        }
        else if (Model.Nivel == 3)
        {
            <div class="progress">
                <div class="progress-bar-success" role="progressbar" aria-valuenow="@Model.Nivel" aria-valuemin="0" aria-valuemax="3" style="width: 100%;">
                    @Model.Nivel
                </div>
            </div>
        }
    </div>
    <br />
    <input type="button" class="btn-danger" name="name" value="Cerrar Sesión" onclick="cerrarSesion()" />
    <br />
    <input type="button" name="name" value="Configuración" onclick="window.location.replace('/Personalizar')" class="btn-info" />
    <br />
    <input type="button" id="btnTienda" value="Regresar" onclick="window.location.replace('/Lobby')" class="btn-success" />
</div>
<div class="row col-md-6" style="background-color:white; height:1000px">
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="M1">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordion" href="#Mejora1" aria-expanded="true" aria-controls="Mejora1">
                        Mejora de Experiencia 
                    </a>
                </h4>
            </div>
            <div id="Mejora1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="M1">
                <div class="panel-body">
                    <img src="~/Content/imagenes/Joystick.png" class="img-circle"/>Con esta mejora ganarás el doble de experiencia por partida.<input type="button" name="name" value="COMPRAR" onclick="comprar(this);" idMejora="1" />    
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="M2">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#Mejora2" aria-expanded="false" aria-controls="Mejora2">
                        Mejora 2
                    </a>
                </h4>
            </div>
            <div id="Mejora2" class="panel-collapse collapse" role="tabpanel" aria-labelledby="M2">
                <div class="panel-body">
                    <img src="~/Content/imagenes/Logo3.png" />Con esta mejora el primer turno atacaras doble.<input type="button" name="name" value="COMPRAR" onclick="comprar(this);" idMejora="2" />
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading" role="tab" id="M3">
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#Mejora3" aria-expanded="false" aria-controls="M3">
                        Mejora 3
                    </a>
                </h4>
            </div>
            <div id="Mejora3" class="panel-collapse collapse" role="tabpanel" aria-labelledby="M3">
                <div class="panel-body">
                    <img src="~/Content/imagenes/Mario.png" /> Con esta mejora puedes atacar doble en un turno durante la partida. <input type="button" name="name" value="COMPRAR" onclick="comprar(this);" idMejora="3" />
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row col-md-3" style="background-color:darkgray;height:800px">
    
</div>

<div id="Comprar" data-url="@Url.Action("ComprarMejora","Tienda")"></div>
<div id="Cancelar" data-url="@Url.Action("Cancelar","Lobby")"></div>

<script type="text/javascript">
    function comprar(e) {
        debugger;
        var mejora = $(e).attr('idMejora');
        $.ajax({
            url: $('#Comprar').attr('data-url'),
            type: 'POST',
            data: { mejora : mejora },
            success: function (resultado) {
                debugger;
                if (resultado.result === true) {
                    alert("Has comprado la mejora!!");
                }
                else {
                    alert('Error al comprar mejora');
                }
            },
            error: function () {
            }
        });
    }

</script>