SiegeCombat/Controllers/PersonalizarController.cs
using SiegeCombat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SiegeCombat.Controllers
{
    public class PersonalizarController : Controller
    {
        //
        // GET: /Personalizar/
        SiegeCombat.Models.SiegeCombatEntities bd = new Models.SiegeCombatEntities();
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult CambiarImagen(string imagen)
         {
             try
             {
                 Jugador temp = (Jugador)Session["Jugador"];
                 Jugador jugador = bd.Jugador.Find(temp.IdJugador);
                 jugador.Imagen = imagen + ".png";
                 bd.Entry(jugador).State = System.Data.EntityState.Modified;
                 bd.SaveChanges();
                 return Json(true);
             }
             catch (Exception ex)
             {
              return null;
             }
         }

        public ActionResult CambiarNickname(string nickname)
        {
            try
            {
                Jugador temp = (Jugador)Session["Jugador"];
                Jugador jugador = bd.Jugador.Find(temp.IdJugador);
                jugador.Nickname = nickname;
                bd.Entry(jugador).State = System.Data.EntityState.Modified;
                bd.SaveChanges();
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

SiegeCombat/Views/Personalizar/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default col-md-6">
    <div class="panel-heading">Configuracion Usuario</div>
    <div class="panel-body">
        <img src="~/Content/imagenes/Mario.png" id="ejemplo"/>
     <label style="font-size:14px">Cambiar Imagen de Jugador</label>       
        <select id="combo" class="form-control" onchange="cambiarImagen();">
            <option id="Mario" value="Mario">Mario</option>
            <option id="Mexico" value="Mexico">México</option>
            <option id="Boo" value="Boo">Boo</option>
            <option id="NewZealand" value="NewZealand">Nueva Zelanda</option>
            <option id="España" value="España">España</option>
        </select>
     <br />
        <label style="font-size:14px">Nickname</label>
        <input type="text" name="name" id="nickname" class="form-control"/>
        <input type="button" id="btnNickname" onclick="cambiarNickname();" value="Cambiar Nickname" class="btn-primary" />
    </div>
</div>

<div id="Imagen" data-url="@Url.Action("CambiarImagen","Personalizar")"></div>
<div id="Nickname" data-url="@Url.Action("CambiarNickname","Personalizar")"></div>

<script>
    function cambiarImagen() {
        debugger;
        var imagen = $("#combo").val();
        $("#ejemplo").attr("src","/Content/imagenes/" + imagen + ".png");
        $.ajax({
            url: $('#Imagen').attr('data-url'),
            type: 'POST',
            data: {imagen : imagen},
            success: function (resultado) {
                debugger;
                if (resultado === true) {
                    alert("Actualizado correctamente");
                }
                else {
                    alert('Error al actualizar');
                }
            },
            error: function () {
            }
        });
    }

    function cambiarNickname() {       
        var nickname = $("#nickname").val();
        debugger;
        $.ajax({
            url: $('#Nickname').attr('data-url'),
            type: 'POST',
            data: {nickname: nickname},
            success: function (resultado) {
                debugger;
                if (resultado === true) {
                    alert("Nickname actualizado correctamente");
                }
                else {
                    alert('Error al actualizar');
                }
            },
            error: function () {
            }
        });
    }
</script>